[metadata]
name = hazdet
version = 0.1.1


[options]
packages = find:
zip_safe = True
include_package_data = True
python_requires = >=3.10
install_requires =
    python-dateutil >= 2.8.2
    pytz >= 2020.1
    scikit-learn >= 1.9.0
    scikit-optimize >= 0.10.2
    scipy >= 1.10
    joblib >= 1.0
    sentence-transformers >= 2.7.0
    transformers >= 4.51.0
    tqdm
    torch >= 2.6.0
    nltk
    sentencepiece
    huggingface-hub >= 0.24.0
    Pillow
    pandas >= 2.2.0
    numpy >= 1.17
    demoji == 1.1.0
    xgboost-cpu >= 2.0.0
    matplotlib >= 3.10.3
